modLoader="javafml"
loaderVersion="[40,)"
license="Not specified"

[[mods]]
modId="obomod"
version="1.1.0"
displayName="OboMod"
credits="Created by: Papela"
displayURL="https://github.com/papela"
updateJSONURL="https://raw.githubusercontent.com/Papela/OboMod/main/updates"
logoFile="logo.png"
authors="Papela, Markos"
description='''
Obo Mod V1.1.0 - 1.18.2
'''

[[dependencies.obomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




